# Generated by Django 3.1 on 2020-08-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_owener'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='owener',
            new_name='owner',
        ),
    ]
